# -*- coding: utf-8 -*-
"""Definicje znaków drogowych - tekst pisany na potrzeby tej aplikacji.

Kody, oficjalne nazwy i nazwy plików z rysunkami leżą osobno, w
narzedzia/znaki-nazwy.json. Tutaj jest tylko to, co trzeba wyjaśnić własnymi
słowami: co znak nakazuje, jak daleko obowiązuje i gdzie zwykle zastawia
pułapkę na egzaminie.

Skrypt zbuduj-znaki.py łączy jedno z drugim w app/data/znaki.json.
"""

# Wspólne zasady dla całej grupy - pokazywane raz, u góry sekcji, żeby nie
# powtarzać ich przy każdym znaku z osobna.
GRUPY = {
    'A': {
        'nazwa': 'Znaki ostrzegawcze',
        'ksztalt': 'Trójkąt z czerwoną obwódką, czarny symbol na żółtym tle.',
        'zasada': (
            'Uprzedzają o niebezpieczeństwie i zobowiązują do zachowania szczególnej '
            'ostrożności. Poza obszarem zabudowanym stoją 150-300 m przed miejscem, '
            'którego dotyczą, w obszarze zabudowanym do 100 m. Inną odległość podaje '
            'tabliczka T-1. Znak ostrzegawczy sam w sobie niczego nie zakazuje ani nie '
            'nakazuje - nie zmienia pierwszeństwa i nie ogranicza prędkości.'
        ),
    },
    'B': {
        'nazwa': 'Znaki zakazu',
        'ksztalt': 'Koło z czerwoną obwódką, czarny symbol na białym tle (wyjątek: ośmiokątny B-20).',
        'zasada': (
            'Zakaz obowiązuje od miejsca ustawienia znaku. Kończy go znak odwołujący, '
            'skrzyżowanie albo znak D-43 (koniec obszaru zabudowanego) - zależnie od znaku. '
            'Znaki odwołujące zakaz nie mają czerwonej obwódki: symbol jest szary i '
            'przekreślony. Napis na znaku lub tabliczka mogą zawęzić zakaz do określonych '
            'godzin, dni albo rodzajów pojazdów.'
        ),
    },
    'C': {
        'nazwa': 'Znaki nakazu',
        'ksztalt': 'Koło niebieskie, biały symbol (wyjątek: prostokątny C-17).',
        'zasada': (
            'Wskazują jedyny dozwolony kierunek jazdy albo narzucają obowiązek. Nakaz '
            'jazdy dotyczy najbliższego skrzyżowania - za nim znak przestaje obowiązywać, '
            'chyba że jest powtórzony. Nie stosuje się do kierujących pojazdami '
            'uprzywilejowanymi ani do zawracania na skrzyżowaniu o ruchu okrężnym.'
        ),
    },
    'D': {
        'nazwa': 'Znaki informacyjne',
        'ksztalt': 'Prostokąt lub kwadrat, najczęściej niebieski (wyjątki: żółte D-1 i D-2, białe D-42 do D-47).',
        'zasada': (
            'Informują o rodzaju drogi, sposobie jej użytkowania i obiektach przy niej. '
            'Część z nich niesie realne obowiązki - D-1 i D-2 rozstrzygają pierwszeństwo, '
            'D-40 i D-42 zmieniają dopuszczalną prędkość i zasady zatrzymywania się.'
        ),
    },
    'E': {
        'nazwa': 'Znaki kierunku i miejscowości',
        'ksztalt': 'Tablice i drogowskazy o kolorze zależnym od rodzaju drogi: zielone (autostrady i ekspresowe), niebieskie, białe, żółte przy objazdach.',
        'zasada': (
            'Same w sobie nie nakazują ani nie zakazują - pokazują, dokąd prowadzą drogi '
            'i gdzie jesteś. Kolor tła mówi o kategorii drogi docelowej, a nie tej, po '
            'której właśnie jedziesz.'
        ),
    },
    'F': {
        'nazwa': 'Znaki uzupełniające',
        'ksztalt': 'Duże prostokąty i kwadraty, niebieskie lub żółte.',
        'zasada': (
            'Uprzedzają o organizacji ruchu, zakazach i zmianach przebiegu drogi, zanim '
            'zaczną obowiązywać. Ostrzegają wcześniej, ale to znak właściwy - a nie znak F - '
            'wprowadza zakaz czy nakaz.'
        ),
    },
    'G': {
        'nazwa': 'Znaki przed przejazdami kolejowymi',
        'ksztalt': 'Słupki wskaźnikowe z ukośnymi kreskami i krzyże św. Andrzeja.',
        'zasada': (
            'Odliczają odległość do przejazdu i wyznaczają miejsce zatrzymania. Krzyż '
            'św. Andrzeja stoi bezpośrednio przed torami i przed nim trzeba się zatrzymać, '
            'jeżeli przejazd nie jest wolny.'
        ),
    },
    'T': {
        'nazwa': 'Tabliczki do znaków',
        'ksztalt': 'Małe prostokąty pod znakiem, białe lub żółte, z czarnym napisem albo symbolem.',
        'zasada': (
            'Tabliczka nigdy nie stoi sama - zmienia znaczenie znaku, pod którym wisi: '
            'zawęża go, rozszerza albo podaje odległość lub długość odcinka. Bez '
            'przeczytania tabliczki znak bywa rozumiany odwrotnie, niż mówi.'
        ),
    },
    'P': {
        'nazwa': 'Znaki poziome',
        'ksztalt': 'Linie i symbole malowane na jezdni, białe (żółte oznaczają oznakowanie tymczasowe, ważniejsze od białego).',
        'zasada': (
            'Mają taką samą moc jak znaki pionowe i uzupełniają je. Gdy oznakowanie '
            'poziome przeczy pionowemu, obowiązuje pionowe. Znaki żółte, malowane przy '
            'robotach drogowych, unieważniają białe.'
        ),
    },
}

OPISY = {
    # ---------------------------------------------------------------- A ----
    'A-1': 'Pojedynczy łuk drogi w prawo, na tyle ostry lub nieprzejrzysty, że wymaga zwolnienia. Zwolnij przed zakrętem, nie w nim - hamowanie na łuku odbiera przyczepność.',
    'A-2': 'To samo co A-1, tylko zakręt prowadzi w lewo. Uważaj na pojazdy z naprzeciwka, bo długie pojazdy na ciasnym łuku wchodzą na środek jezdni.',
    'A-3': 'Co najmniej dwa zakręty następujące po sobie w odstępie mniejszej niż 300 m; pierwszy jest w prawo. Liczbę zakrętów podaje tabliczka T-4, a długość odcinka T-2.',
    'A-4': 'Seria zakrętów, z których pierwszy prowadzi w lewo. Poza tym znaczenie identyczne jak A-3.',
    'A-5': 'Skrzyżowanie dróg równorzędnych - żadna droga nie ma pierwszeństwa. Obowiązuje reguła prawej ręki: ustępujesz pojazdowi nadjeżdżającemu z prawej strony. Znak nie daje Ci pierwszeństwa, tylko uprzedza, że nikt go tu nie ma.',
    'A-6a': 'Zbliżasz się do skrzyżowania jako kierujący na drodze z pierwszeństwem; drogi podporządkowane dochodzą z obu stron. Pierwszeństwo masz Ty, ale ostrożność nadal obowiązuje.',
    'A-6b': 'Jedziesz drogą z pierwszeństwem, droga podporządkowana dochodzi z prawej strony.',
    'A-6c': 'Jedziesz drogą z pierwszeństwem, droga podporządkowana dochodzi z lewej strony.',
    'A-6d': 'Z prawej strony dochodzi wlot drogi jednokierunkowej - pojazdy mogą stamtąd wyjeżdżać, ale nie da się w nią wjechać.',
    'A-6e': 'Wlot drogi jednokierunkowej z lewej strony. Znaczenie jak A-6d.',
    'A-7': 'Musisz ustąpić pierwszeństwa pojazdom na drodze z pierwszeństwem. Zatrzymanie nie jest obowiązkowe, jeżeli droga jest wolna - ale trzeba się zatrzymać, gdy inaczej nie da się ustąpić. Odwrócony trójkąt jest rozpoznawalny nawet od tyłu i po zaśnieżeniu, dlatego ma taki kształt.',
    'A-8': 'Uprzedza o skrzyżowaniu o ruchu okrężnym. Sam nie rozstrzyga pierwszeństwa - robi to dopiero znak A-7 lub B-20 przy wjeździe. Bez nich obowiązuje reguła prawej ręki.',
    'A-9': 'Przejazd kolejowy wyposażony w zapory lub półzapory. Nie wjeżdżaj, jeżeli zapora zaczyna się opuszczać albo jest opuszczona, i nie omijaj półzapór.',
    'A-10': 'Przejazd bez zapór - o bezpieczeństwie decyduje wyłącznie Twoja obserwacja torów. Zbliżaj się z prędkością pozwalającą zatrzymać się przed torami.',
    'A-11': 'Uszkodzona nawierzchnia: koleiny, wyboje, ubytki. Grozi utratą przyczepności i uszkodzeniem zawieszenia.',
    'A-11a': 'Sztucznie wykonany garb spowalniający ruch. Przejeżdżaj powoli i prostopadle.',
    'A-12a': 'Jezdnia zwęża się z obu stron. Znak nie mówi, kto ma pierwszeństwo - to rozstrzygają dopiero znaki B-31 albo D-5.',
    'A-12b': 'Jezdnia zwęża się od prawej strony.',
    'A-12c': 'Jezdnia zwęża się od lewej strony.',
    'A-13': 'Most zwodzony lub obrotowy, który bywa otwierany dla żeglugi. Przy otwarciu ruch jest wstrzymywany sygnalizacją lub zaporami.',
    'A-14': 'Prace na drodze lub w jej bezpośrednim sąsiedztwie. Spodziewaj się ludzi i maszyn na jezdni, zwężeń oraz tymczasowego oznakowania - żółte linie poziome mają wtedy pierwszeństwo przed białymi.',
    'A-15': 'Odcinek, na którym przyczepność bywa nagle mniejsza - z powodu deszczu, błota, wilgotnych liści albo wygładzonej nawierzchni. Wydłuż odstęp i unikaj gwałtownych ruchów kierownicą.',
    'A-16': 'Uprzedza o przejściu dla pieszych. Nie myl go z D-6: A-16 jest trójkątny i stoi przed przejściem, D-6 jest niebieskim kwadratem i oznacza samo przejście.',
    'A-17': 'Miejsce, gdzie dzieci często wchodzą na jezdnię - zwykle przy szkole albo placu zabaw. Licz się z zachowaniem całkowicie nieprzewidywalnym.',
    'A-18a': 'Możliwość napotkania zwierząt gospodarskich lub ich stada na drodze, często pod opieką poganiacza.',
    'A-18b': 'Odcinek, na którym często przebiegają dzikie zwierzęta. Jeżeli jedno przebiegło, spodziewaj się kolejnych - poruszają się stadami.',
    'A-19': 'Silny wiatr boczny, zwykle na mostach, wiaduktach i wyjazdach z lasu. Najgroźniejszy dla pojazdów wysokich i z przyczepą; trzymaj kierownicę mocniej przy wyjeździe z osłony.',
    'A-20': 'Kończy się droga jednokierunkowa - dalej jedziesz odcinkiem dwukierunkowym. Wracaj na prawą stronę jezdni i licz się z pojazdami z naprzeciwka.',
    'A-21': 'Miejsce, w którym tory tramwajowe przecinają drogę lub biegną blisko niej, bez sygnalizacji ostrzegawczej. Tramwaj ma dłuższą drogę hamowania i nie może skręcić.',
    'A-22': 'Stromy spadek drogi; liczba na znaku podaje nachylenie w procentach. Zjeżdżaj na niskim biegu, żeby nie przegrzać hamulców.',
    'A-23': 'Stromy podjazd. Redukuj bieg zawczasu; przy wąskiej drodze górskiej pierwszeństwo ma pojazd jadący pod górę.',
    'A-24': 'Miejsce, gdzie rowerzyści wjeżdżają na jezdnię albo ją przecinają - zwykle wylot drogi dla rowerów.',
    'A-25': 'Możliwość obsuwania się kamieni ze skarpy. Nie zatrzymuj się na takim odcinku bez potrzeby i uważaj na odłamki leżące na jezdni.',
    'A-26': 'Odcinek, nad którym nisko przelatują samoloty. Ostrzega przed hałasem i nagłym cieniem, które potrafią zaskoczyć kierującego.',
    'A-27': 'Droga kończy się nabrzeżem lub urywa przy brzegu, bez bariery. Realne ryzyko wjechania do wody.',
    'A-28': 'Luźny żwir na nawierzchni. Zmniejsz prędkość i zwiększ odstęp - kamienie wyrzucane spod kół uszkadzają szyby jadących z tyłu.',
    'A-29': 'Sygnalizacja świetlna w miejscu, gdzie kierujący może się jej nie spodziewać. Jedyny znak ostrzegawczy z kolorowym symbolem.',
    'A-30': 'Niebezpieczeństwo, dla którego nie przewidziano osobnego znaku. Rodzaj zagrożenia podaje tabliczka pod znakiem - bez niej znak niewiele mówi, więc tabliczkę trzeba przeczytać.',
    'A-31': 'Pobocze nieutwardzone, obniżone lub grząskie po prawej stronie. Zjazd kołem na takie pobocze przy prędkości potrafi ściągnąć pojazd z drogi.',
    'A-31a': 'To samo niebezpieczne pobocze, ale po lewej stronie drogi.',
    'A-32': 'Odcinek szczególnie podatny na oblodzenie - mosty, wiadukty, zagłębienia terenu, odcinki w cieniu. Szron pojawia się tam wcześniej niż na reszcie drogi.',
    'A-33': 'Zator drogowy albo miejsce, gdzie tworzy się on regularnie. Zwykle znak o zmiennej treści, włączany na czas utrudnień.',
    'A-34': 'Wypadek blokujący drogę na wskazanym odcinku. Licz się z ludźmi na jezdni i z pojazdami służb ratowniczych.',

    # ---------------------------------------------------------------- B ----
    'B-1': 'Zakaz ruchu wszelkich pojazdów w obu kierunkach, a także kolumn pieszych, jeźdźców i poganiaczy. Nie dotyczy pieszych idących pojedynczo. Tabliczka „Nie dotyczy…” wyłącza spod zakazu wskazany rodzaj pojazdu.',
    'B-2': 'Zakaz wjazdu z tej strony - stoi na wylocie drogi jednokierunkowej. Po drugiej stronie tej samej drogi jest znak D-3. Nie oznacza zakazu ruchu na całej drodze, tylko zakazu wjazdu w tym miejscu.',
    'B-3': 'Zakaz wjazdu pojazdów silnikowych z wyjątkiem motocykli jednośladowych. Motocykl z wózkiem bocznym już nie może wjechać.',
    'B-3a': 'Zakaz wjazdu autobusów. Dotyczy pojazdów przeznaczonych do przewozu więcej niż 9 osób z kierowcą.',
    'B-4': 'Zakaz wjazdu motocykli - wszystkich, także jednośladowych.',
    'B-5': 'Zakaz wjazdu samochodów ciężarowych o dopuszczalnej masie całkowitej powyżej 3,5 t, ciągników samochodowych i pojazdów specjalnych. Liczba na znaku obniża ten próg. Dotyczy też ciągnika z naczepą.',
    'B-5a': 'Zakaz wjazdu pojazdów i zespołów pojazdów o dopuszczalnej masie całkowitej większej niż podana na znaku - niezależnie od tego, czy to ciężarówka, czy osobowy z przyczepą.',
    'B-6': 'Zakaz wjazdu ciągników rolniczych i pojazdów wolnobieżnych.',
    'B-7': 'Zakaz wjazdu pojazdów silnikowych z przyczepą. Nie dotyczy przyczep jednoosiowych i naczep. Liczba na znaku ogranicza zakaz do przyczep cięższych niż podana masa.',
    'B-8': 'Zakaz wjazdu pojazdów zaprzęgowych, czyli ciągniętych przez zwierzęta.',
    'B-9': 'Zakaz wjazdu rowerów. Rowerzysta może tędy przejść, prowadząc rower - wtedy jest pieszym.',
    'B-10': 'Zakaz wjazdu motorowerów.',
    'B-11': 'Zakaz wjazdu wózków rowerowych, czyli pojazdów wielośladowych napędzanych siłą mięśni.',
    'B-12': 'Zakaz wjazdu wózków ręcznych - prowadzonych lub ciągniętych przez pieszego.',
    'B-13': 'Zakaz wjazdu pojazdów przewożących towary wybuchowe lub łatwo zapalne.',
    'B-13a': 'Zakaz wjazdu pojazdów przewożących jakiekolwiek towary niebezpieczne w ilościach objętych przepisami ADR.',
    'B-14': 'Zakaz wjazdu pojazdów z towarami mogącymi skazić wodę. Stawiany zwykle przy ujęciach wody i zbiornikach.',
    'B-15': 'Zakaz wjazdu pojazdów szerszych niż podano na znaku. Liczy się szerokość z ładunkiem, także wystającym.',
    'B-16': 'Zakaz wjazdu pojazdów wyższych niż podano - przed wiaduktami, tunelami i bramami. Wysokość mierzy się z ładunkiem.',
    'B-17': 'Zakaz wjazdu pojazdów dłuższych niż podano. Dla zespołu pojazdów liczy się długość całości.',
    'B-18': 'Zakaz wjazdu pojazdów o rzeczywistej masie całkowitej ponad podaną wartość. Uwaga: chodzi o masę faktyczną w danej chwili, razem z ładunkiem - a nie o dopuszczalną z dowodu rejestracyjnego.',
    'B-19': 'Zakaz wjazdu pojazdów o nacisku osi większym niż podany. Stawiany na drogach o słabszej konstrukcji.',
    'B-20': 'Musisz się zatrzymać przed skrzyżowaniem lub torami, nawet gdy droga jest zupełnie pusta, a dopiero potem ustąpić pierwszeństwa. Ośmiokątny kształt pozwala rozpoznać znak od tyłu i pod śniegiem. Zatrzymanie ma nastąpić w miejscu wyznaczonym linią P-12, a gdy jej nie ma - w miejscu, z którego widać drogę.',
    'B-21': 'Zakaz skręcania w lewo za znakiem, obejmujący także zawracanie. Obowiązuje na najbliższym skrzyżowaniu.',
    'B-22': 'Zakaz skręcania w prawo na najbliższym skrzyżowaniu.',
    'B-23': 'Zakaz zawracania. Obowiązuje do najbliższego skrzyżowania włącznie albo do znaku B-24.',
    'B-24': 'Odwołuje zakaz zawracania wprowadzony znakiem B-23.',
    'B-25': 'Zakaz wyprzedzania pojazdów silnikowych wielośladowych. Można wyprzedzać rower, motorower i motocykl jednośladowy. Zakaz kończy się na skrzyżowaniu albo przy znaku B-27.',
    'B-26': 'Zakaz wyprzedzania dotyczy tylko samochodów ciężarowych o dmc powyżej 3,5 t, ciągników samochodowych i pojazdów specjalnych. Pozostałych kierujących nie ogranicza.',
    'B-27': 'Odwołuje zakaz wyprzedzania z B-25.',
    'B-28': 'Odwołuje zakaz wyprzedzania przez samochody ciężarowe z B-26.',
    'B-29': 'Zakaz używania sygnałów dźwiękowych. Nie dotyczy sytuacji, w której sygnał ostrzega przed bezpośrednim niebezpieczeństwem.',
    'B-30': 'Odwołuje zakaz z B-29.',
    'B-31': 'Na zwężonym odcinku pierwszeństwo mają nadjeżdżający z przeciwka - to Ty ustępujesz. Po przeciwnej stronie zwężenia stoi D-5. Czerwona strzałka pokazuje kierunek uprzywilejowany.',
    'B-32': 'Nakaz zatrzymania się w celu kontroli. Napis na znaku mówi, czego kontrola dotyczy: celna, graniczna, sanitarna, pobór opłat, wjazd na prom, uszkodzona rogatka lub sygnalizacja. Wolno ruszyć dopiero po zezwoleniu.',
    'B-33': 'Zakaz przekraczania prędkości podanej na znaku. Obowiązuje do najbliższego skrzyżowania, do znaku B-34, do kolejnego B-33 albo do znaku D-42 lub D-43, gdy te wprowadzają niższy limit.',
    'B-34': 'Odwołuje ograniczenie prędkości z B-33 - dalej obowiązują limity ogólne właściwe dla danej drogi.',
    'B-35': 'Zakaz postoju: możesz się zatrzymać na czas do 1 minuty, a także dłużej, jeżeli wsiadają lub wysiadają pasażerowie albo trwa załadunek. Postój, czyli dłuższe unieruchomienie, jest zabroniony.',
    'B-36': 'Zakaz zatrzymywania się, czyli surowszy od B-35 - nie wolno unieruchomić pojazdu nawet na chwilę, poza sytuacjami wymuszonymi warunkami ruchu. Zasięg wskazują tabliczki T-24, T-25 i strzałki na znaku.',
    'B-37': 'Zakaz postoju w dni nieparzyste, obowiązujący od godziny 21 dnia poprzedzającego.',
    'B-38': 'Zakaz postoju w dni parzyste, na tych samych zasadach co B-37. Oba znaki działają razem po dwóch stronach ulicy i wymuszają cykliczne przestawianie pojazdu.',
    'B-39': 'Wjazd do strefy, w której obowiązują szczególne zasady postoju podane na znaku. Zakaz działa w całej strefie, także na drogach bez powtórzonych znaków - aż do B-40.',
    'B-40': 'Koniec strefy ograniczonego postoju.',
    'B-41': 'Zakaz ruchu pieszych po tej stronie drogi. Kierującego nie dotyczy, ale uprzedza, że pieszy tu być nie powinien.',
    'B-42': 'Odwołuje wszystkie wcześniej wprowadzone zakazy naraz - jednym znakiem zamiast kilku odwołań. Nie dotyczy zakazów strefowych ani zakazu zatrzymywania się i postoju.',
    'B-43': 'Wjazd do strefy z ograniczoną prędkością podaną na znaku. Ograniczenie obowiązuje na wszystkich drogach w strefie, także za skrzyżowaniami, aż do znaku B-44.',
    'B-44': 'Koniec strefy ograniczonej prędkości.',

    # ---------------------------------------------------------------- C ----
    'C-1': 'Nakaz jazdy w prawo przed znakiem - skręcasz przed tarczą znaku, która stoi na wprost wylotu.',
    'C-2': 'Nakaz jazdy w prawo za znakiem - skręcasz dopiero za nim, czyli na skrzyżowaniu. Różnica między C-1 a C-2 to miejsce skrętu i właśnie ona bywa sprawdzana.',
    'C-3': 'Nakaz jazdy w lewo przed znakiem.',
    'C-4': 'Nakaz jazdy w lewo za znakiem.',
    'C-5': 'Nakaz jazdy prosto. Zakazuje skręcania w obie strony i zawracania na najbliższym skrzyżowaniu.',
    'C-6': 'Dozwolona jazda prosto albo w prawo - skręt w lewo i zawracanie są zakazane.',
    'C-7': 'Dozwolona jazda prosto albo w lewo.',
    'C-8': 'Dozwolony skręt w prawo albo w lewo, jazda prosto jest zabroniona.',
    'C-9': 'Nakaz ominięcia przeszkody z prawej strony - znak stoi na wysepce lub przy przeszkodzie na jezdni.',
    'C-10': 'Nakaz ominięcia przeszkody z lewej strony.',
    'C-11': 'Przeszkodę wolno ominąć z dowolnej strony.',
    'C-12': 'Ruch odbywa się dookoła wyspy w kierunku wskazanym strzałkami. Sam znak nie daje pierwszeństwa jadącym po rondzie - robi to dopiero A-7 lub B-20 na wlocie. Bez nich obowiązuje reguła prawej ręki.',
    'C-13': 'Droga przeznaczona dla rowerów; rowerzysta ma obowiązek z niej korzystać. Kierujący innym pojazdem nie może na nią wjechać.',
    'C-13a': 'Koniec drogi dla rowerów - symbol przekreślony.',
    'C-14': 'Nakaz jazdy z prędkością nie mniejszą niż podana, o ile pozwalają na to warunki. Jazda wolniej tamuje ruch.',
    'C-15': 'Koniec obowiązku jazdy z prędkością minimalną.',
    'C-16': 'Droga lub jej część przeznaczona dla pieszych; pieszy ma obowiązek z niej korzystać. Wjazd pojazdów jest zabroniony.',
    'C-16a': 'Koniec drogi dla pieszych.',
    'C-17': 'Nakazany kierunek jazdy dla pojazdów z towarami niebezpiecznymi. Jedyny znak nakazu na prostokątnej tablicy o białym tle.',
    'C-18': 'Nakaz jazdy z łańcuchami przeciwpoślizgowymi na co najmniej dwóch kołach osi napędowej. Stosowany na drogach górskich zimą.',
    'C-19': 'Koniec nakazu używania łańcuchów przeciwpoślizgowych.',

    # ---------------------------------------------------------------- D ----
    'D-1': 'Jedziesz drogą z pierwszeństwem - na kolejnych skrzyżowaniach masz pierwszeństwo przed wjeżdżającymi z dróg poprzecznych. Żółty kwadrat postawiony na wierzchołku jest rozpoznawalny nawet od tyłu. Jeżeli pod znakiem jest tabliczka T-6a, droga z pierwszeństwem skręca - gruba linia pokazuje jej faktyczny przebieg i wtedy trzeba jechać po niej, a nie na wprost.',
    'D-2': 'Kończy się droga z pierwszeństwem. Od najbliższego skrzyżowania obowiązuje reguła prawej ręki albo oznakowanie ustawione na miejscu.',
    'D-3': 'Droga jednokierunkowa. Nie ma tu ruchu z naprzeciwka, więc wolno wyprzedzać z obu stron, a przy zawracaniu i zatrzymywaniu obowiązują inne zasady niż na drodze dwukierunkowej. Na drugim końcu tej samej drogi stoi B-2.',
    'D-4a': 'Droga bez przejazdu - kończy się ślepo, nie da się nią wyjechać na inną. Nie jest to zakaz wjazdu, tylko ostrzeżenie, że trzeba będzie zawrócić.',
    'D-4b': 'Wjazd na drogę bez przejazdu; znak stoi przy skrzyżowaniu i pokazuje, który wlot jest ślepy.',
    'D-5': 'Na zwężonym odcinku masz pierwszeństwo przed nadjeżdżającymi z przeciwka. To odwrotność znaku B-31, który stoi po drugiej stronie zwężenia.',
    'D-6': 'Oznacza samo przejście dla pieszych. Zbliżając się, musisz zachować szczególną ostrożność, ustąpić pierwszeństwa pieszemu na przejściu i wchodzącemu na nie. Zabronione jest wyprzedzanie na przejściu i bezpośrednio przed nim. Nie myl z trójkątnym A-16, który tylko uprzedza o przejściu.',
    'D-6a': 'Przejazd dla rowerzystów. Zbliżając się, ustępujesz pierwszeństwa rowerzyście znajdującemu się na przejeździe.',
    'D-6b': 'Przejście dla pieszych i przejazd dla rowerzystów w jednym miejscu.',
    'D-7': 'Początek drogi ekspresowej. Obowiązują wyższe limity prędkości, zakaz zawracania, zakaz ruchu pieszych, rowerów i pojazdów wolnobieżnych oraz zakaz zatrzymywania się poza wyznaczonymi miejscami.',
    'D-8': 'Koniec drogi ekspresowej - od tego miejsca obowiązują zwykłe zasady i limity.',
    'D-9': 'Początek autostrady. Zasady jak na drodze ekspresowej, ale limit prędkości jest najwyższy, a jezdnie zawsze rozdzielone.',
    'D-10': 'Koniec autostrady.',
    'D-11': 'Początek pasa ruchu przeznaczonego dla autobusów. Innym pojazdom nie wolno nim jechać, chyba że znak lub tabliczka stanowi inaczej.',
    'D-12': 'Pas ruchu dla autobusów - powtórzenie informacji na dalszym odcinku.',
    'D-13': 'Początek pasa ruchu powolnego, przeznaczonego dla pojazdów jadących wolno, zwykle na długim podjeździe.',
    'D-13a': 'Początek dodatkowego pasa ruchu; strzałki pokazują, jak układają się pasy.',
    'D-13b': 'Początek pasa ruchu na jezdni dwukierunkowej.',
    'D-14': 'Koniec pasa ruchu - pas zanika i trzeba zjechać na sąsiedni, ustępując pierwszeństwa jadącym po nim.',
    'D-15': 'Przystanek autobusowy. Zatrzymywanie się w odległości 15 m od znaku jest zabronione, a poza obszarem zabudowanym trzeba ułatwić autobusowi włączenie się do ruchu.',
    'D-16': 'Przystanek trolejbusowy - zasady jak przy D-15.',
    'D-17': 'Przystanek tramwajowy. Gdy nie ma wysepki, a tramwaj stoi, musisz zatrzymać się za nim i przepuścić pasażerów wsiadających i wysiadających.',
    'D-18': 'Parking. Tabliczki pod znakiem mogą określać sposób ustawienia pojazdu, dozwolony czas postoju albo grupę uprawnionych.',
    'D-18a': 'Parking z miejscami zastrzeżonymi dla określonych pojazdów - wskazuje je tabliczka.',
    'D-18b': 'Parking zadaszony lub w budynku.',
    'D-19': 'Postój taksówek. Innym pojazdom nie wolno tu stawać.',
    'D-20': 'Koniec postoju taksówek.',
    'D-21': 'Szpital. Uprzedza o możliwym ruchu karetek i o tym, że warto ograniczyć hałas.',
    'D-21a': 'Jednostka policji.',
    'D-22': 'Punkt opatrunkowy - miejsce udzielania pierwszej pomocy.',
    'D-23': 'Stacja paliwowa.',
    'D-23a': 'Stacja wyłącznie z gazem do napędu pojazdów.',
    'D-23b': 'Stacja paliwowa z punktem ładowania pojazdów elektrycznych.',
    'D-23c': 'Punkt ładowania pojazdów elektrycznych.',
    'D-24': 'Telefon ogólnodostępny.',
    'D-25': 'Placówka pocztowa.',
    'D-25a': 'Poczta z ogólnodostępnym telefonem.',
    'D-26': 'Stacja obsługi technicznej pojazdów.',
    'D-26a': 'Punkt wulkanizacyjny.',
    'D-26b': 'Myjnia samochodowa.',
    'D-26c': 'Toaleta publiczna.',
    'D-26d': 'Natryski.',
    'D-27': 'Bufet lub kawiarnia.',
    'D-28': 'Restauracja.',
    'D-29': 'Hotel lub motel.',
    'D-30': 'Obozowisko (kemping).',
    'D-31': 'Kemping z podłączeniami elektrycznymi dla przyczep kempingowych.',
    'D-32': 'Pole biwakowe.',
    'D-33': 'Schronisko młodzieżowe.',
    'D-34': 'Punkt informacji turystycznej.',
    'D-34a': 'Częstotliwość radiowa, na której nadawane są komunikaty o ruchu drogowym.',
    'D-34b': 'Zbiorcza tablica z informacjami o obiektach przy drodze.',
    'D-35': 'Przejście podziemne dla pieszych. Jeżeli jest wyznaczone, pieszy ma obowiązek z niego korzystać.',
    'D-35a': 'Schody ruchome prowadzące w dół, przy przejściu dla pieszych.',
    'D-36': 'Przejście nadziemne dla pieszych, czyli kładka.',
    'D-36a': 'Schody ruchome prowadzące w górę.',
    'D-37': 'Tunel. Obowiązuje jazda z włączonymi światłami mijania, zakaz zawracania i cofania oraz zakaz zatrzymywania się poza miejscami wyznaczonymi.',
    'D-38': 'Koniec tunelu.',
    'D-39': 'Tablica przypominająca dopuszczalne prędkości obowiązujące w Polsce. Stawiana przy przejściach granicznych.',
    'D-39a': 'Informacja o opłatach za przejazd drogą.',
    'D-40': 'Początek strefy zamieszkania. Pieszy może korzystać z całej szerokości drogi i ma pierwszeństwo przed pojazdami, prędkość jest ograniczona do 20 km/h, a postój dozwolony tylko w miejscach wyznaczonych. Wyjeżdżając ze strefy, włączasz się do ruchu i ustępujesz wszystkim.',
    'D-41': 'Koniec strefy zamieszkania.',
    'D-42': 'Początek obszaru zabudowanego. Prędkość ograniczona do 50 km/h przez całą dobę. Zmieniają się też zasady dotyczące holowania i zatrzymywania.',
    'D-43': 'Koniec obszaru zabudowanego - dalej obowiązują limity dla dróg poza obszarem zabudowanym. Znak ten odwołuje również wcześniejsze ograniczenie prędkości wprowadzone znakiem B-33.',
    'D-44': 'Wjazd do strefy płatnego parkowania. Za postój trzeba wnieść opłatę w sposób podany na znaku.',
    'D-45': 'Koniec strefy płatnego parkowania.',
    'D-46': 'Początek drogi wewnętrznej - nie jest drogą publiczną, ale przepisy ruchu drogowego nadal obowiązują.',
    'D-47': 'Koniec drogi wewnętrznej.',
    'D-48': 'Uprzedza, że na najbliższym skrzyżowaniu zmieniono dotychczasowe pierwszeństwo. Znak stawia się na krótko po zmianie organizacji ruchu, właśnie po to, żeby przyzwyczajenie nie doprowadziło do wypadku.',
    'D-49': 'Miejsce poboru opłat za przejazd.',
    'D-50': 'Zatoka przy drodze, przeznaczona do zatrzymania się poza jezdnią.',
    'D-51': 'Automatyczna kontrola prędkości w tym miejscu - fotoradar.',
    'D-51a': 'Początek odcinkowego pomiaru prędkości: liczy się średnia prędkość na całym odcinku, a nie w jednym punkcie.',
    'D-51b': 'Koniec odcinka objętego pomiarem średniej prędkości.',
    'D-52': 'Początek strefy ruchu - terenu niebędącego drogą publiczną, ale ogólnodostępnego, np. osiedla lub parkingu przy markecie. Obowiązują na nim wszystkie przepisy ruchu drogowego wraz z odpowiedzialnością za wykroczenia.',
    'D-53': 'Koniec strefy ruchu.',
    'D-54': 'Wjazd do strefy czystego transportu, do której mogą wjeżdżać tylko pojazdy spełniające określone normy emisji.',
    'D-55': 'Koniec strefy czystego transportu.',

    # ---------------------------------------------------------------- E ----
    'E-1': 'Tablica przeddrogowskazowa - uprzedza o skrzyżowaniu i pokazuje jego układ oraz kierunki. Umieszczone na niej miniatury innych znaków zapowiadają, co spotkasz na wskazanych drogach.',
    'E-1a': 'Tablica przeddrogowskazowa na autostradzie - zielona, umieszczana nad jezdnią lub obok niej przed węzłem.',
    'E-2a': 'Drogowskaz tablicowy obok jezdni - pokazuje kierunki na najbliższym skrzyżowaniu.',
    'E-2b': 'Ten sam drogowskaz umieszczony nad jezdnią, gdy pasy ruchu prowadzą w różne strony.',
    'E-2d': 'Drogowskaz tablicowy nad jezdnią autostrady lub drogi ekspresowej.',
    'E-2e': 'Drogowskaz obok jezdni przed wjazdem na autostradę.',
    'E-3': 'Drogowskaz w kształcie strzały do miejscowości, z numerem drogi. Strzała wskazuje kierunek jazdy.',
    'E-3a': 'Wersja drogowskazu strzałowego z dwiema miejscowościami kierunkowymi.',
    'E-4': 'Drogowskaz strzałowy podający odległość do miejscowości w kilometrach.',
    'E-5': 'Drogowskaz do miejscowości lub dzielnicy bez podania odległości.',
    'E-5a': 'Drogowskaz do centrum miasta.',
    'E-6': 'Drogowskaz do lotniska.',
    'E-6a': 'Drogowskaz do dworca lub stacji kolejowej.',
    'E-6b': 'Drogowskaz do dworca autobusowego.',
    'E-6c': 'Drogowskaz do przystani promowej.',
    'E-7': 'Drogowskaz do przystani wodnej lub żeglugi.',
    'E-8': 'Drogowskaz do plaży lub miejsca kąpielowego.',
    'E-9': 'Drogowskaz do muzeum.',
    'E-10': 'Drogowskaz do zabytku będącego dobrem kultury.',
    'E-11': 'Drogowskaz do pomnika przyrody.',
    'E-12': 'Drogowskaz do punktu widokowego.',
    'E-12a': 'Drogowskaz do szlaku rowerowego.',
    'E-13': 'Tablica kierunkowa - wskazuje kierunki i odległości do miejscowości leżących przy tej samej drodze.',
    'E-14': 'Tablica szlaku drogowego - podaje kolejne miejscowości i odległości na trasie, którą właśnie jedziesz.',
    'E-15a': 'Numer drogi krajowej.',
    'E-15b': 'Numer drogi wojewódzkiej.',
    'E-15c': 'Numer autostrady.',
    'E-15d': 'Numer drogi ekspresowej.',
    'E-16': 'Numer szlaku międzynarodowego, oznaczany literą E i liczbą, na zielonym tle.',
    'E-17a': 'Początek miejscowości. Sam w sobie nie wprowadza ograniczenia prędkości - robi to dopiero znak D-42.',
    'E-18a': 'Koniec miejscowości. Podobnie jak E-17a, nie zmienia limitu prędkości - ten odwołuje D-43.',
    'E-19a': 'Obwodnica - droga omijająca miejscowość.',
    'E-20': 'Tablica węzła drogowego, zapowiadająca zjazd z autostrady lub drogi ekspresowej.',
    'E-20a': 'Numer węzła drogowego na autostradzie lub drodze ekspresowej.',
    'E-21': 'Nazwa dzielnicy lub osiedla.',
    'E-22a': 'Samochodowy szlak turystyczny.',
    'E-22b': 'Obiekt leżący na samochodowym szlaku turystycznym.',
    'E-22c': 'Informacja o obiektach turystycznych w okolicy.',

    # ---------------------------------------------------------------- F ----
    'F-1': 'Czynne przejście graniczne.',
    'F-2': 'Ruch przez granicę w tym miejscu jest zamknięty.',
    'F-2a': 'Miejsce przekroczenia granicy państwa wewnątrz strefy Schengen, bez kontroli.',
    'F-3': 'Granica obszaru administracyjnego - województwa, powiatu lub gminy.',
    'F-3a': 'Granica powiatu.',
    'F-3b': 'Granica gminy.',
    'F-3c': 'Granica miasta na prawach powiatu.',
    'F-4': 'Nazwa rzeki, nad którą przejeżdżasz.',
    'F-5': 'Uprzedza o zakazie, który zacznie obowiązywać dalej - podaje rodzaj zakazu i odległość do niego.',
    'F-6': 'Zapowiada przed skrzyżowaniem, jakie znaki obowiązują na drogach odchodzących od niego. Pozwala wybrać pas, zanim będzie za późno.',
    'F-6a': 'Wariant znaku uprzedzającego o organizacji ruchu na skrzyżowaniu.',
    'F-7': 'Pokazuje, jak dojechać w lewo, gdy skręcanie w lewo jest zabronione - zwykle przez objazd wokół kwartału.',
    'F-8': 'Objazd w związku z zamknięciem drogi. Żółte tło oznacza organizację tymczasową.',
    'F-9': 'Znak prowadzący po trasie objazdu - potwierdza, że nadal jedziesz właściwą drogą.',
    'F-10': 'Pokazuje, dokąd prowadzi każdy z pasów ruchu na najbliższym skrzyżowaniu. Wybór pasa trzeba zrobić przed skrzyżowaniem, bo na nim zmiana pasa bywa niemożliwa.',
    'F-11': 'To samo co F-10, ale dla jednego wybranego pasa ruchu.',
    'F-12': 'Wskazuje przed skrzyżowaniem przebieg trasy tranzytowej.',
    'F-13': 'Potwierdza przebieg przejazdu tranzytowego przez miejscowość.',
    'F-14a': 'Tablica wskaźnikowa na autostradzie - 300 m do pasa wyłączania. Trzy ukośne kreski.',
    'F-14b': 'Tablica wskaźnikowa na autostradzie - 200 m do pasa wyłączania. Dwie kreski.',
    'F-14c': 'Tablica wskaźnikowa na autostradzie - 100 m do pasa wyłączania. Jedna kreska.',
    'F-14d': 'Tablica wskaźnikowa na drodze ekspresowej - 300 m do pasa wyłączania.',
    'F-14e': 'Tablica wskaźnikowa na drodze ekspresowej - 200 m do pasa wyłączania.',
    'F-14f': 'Tablica wskaźnikowa na drodze ekspresowej - 100 m do pasa wyłączania.',
    'F-15': 'Niesymetryczny podział jezdni: kierunki mają różną liczbę pasów.',
    'F-16': 'Zapowiada koniec pasa ruchu na jezdni dwukierunkowej - trzeba zjechać na sąsiedni pas.',
    'F-17': 'Zapowiada koniec pasa ruchu na jezdni jednokierunkowej.',
    'F-18': 'Na wskazanym pasie odbywa się ruch w przeciwnym kierunku, dozwolony tylko dla określonych pojazdów - najczęściej autobusów.',
    'F-19': 'Pas przeznaczony dla określonego rodzaju pojazdów, wskazanego na znaku.',
    'F-20': 'Część drogi lub pas przeznaczony dla określonych pojazdów.',
    'F-21': 'Ruch został przeniesiony na sąsiednią jezdnię - typowe przy remontach dróg dwujezdniowych.',
    'F-22': 'Podaje ograniczenia obowiązujące na poszczególnych pasach ruchu, np. dopuszczalną masę lub wysokość.',
    'F-23': 'Środkowy pas wielofunkcyjny, z którego korzystają naprzemiennie oba kierunki przy skręcaniu w lewo.',
    'F-24': 'Ostrzega, że jedziesz pod prąd - ustawiany na wjazdach na drogi jednokierunkowe, autostrady i ekspresowe. Natychmiast zatrzymaj się i zawróć poza jezdnią.',

    # ---------------------------------------------------------------- G ----
    'G-1a': 'Słupek z trzema kreskami po prawej stronie - do przejazdu kolejowego zostało około 240 m.',
    'G-1b': 'Słupek z dwiema kreskami po prawej stronie - około 160 m do przejazdu.',
    'G-1c': 'Słupek z jedną kreską po prawej stronie - około 80 m do przejazdu. Im mniej kresek, tym bliżej torów.',
    'G-1d': 'Słupek z trzema kreskami po lewej stronie jezdni.',
    'G-1e': 'Słupek z dwiema kreskami po lewej stronie jezdni.',
    'G-1f': 'Słupek z jedną kreską po lewej stronie jezdni.',
    'G-2': 'Sieć trakcyjna pod napięciem nad przejazdem. Ostrzega przed dotknięciem przewodów wysokim ładunkiem.',
    'G-3': 'Krzyż św. Andrzeja przed przejazdem jednotorowym. Wyznacza miejsce zatrzymania, gdy przejazd nie jest wolny.',
    'G-4': 'Krzyż św. Andrzeja przed przejazdem wielotorowym - podwójny. Po przejeździe jednego pociągu może nadjeżdżać drugi z przeciwnej strony.',

    # ---------------------------------------------------------------- T ----
    'T-1': 'Podaje odległość znaku ostrzegawczego od miejsca niebezpiecznego, gdy różni się ona od typowej.',
    'T-1a': 'Odległość znaku informacyjnego od początku lub końca drogi, odcinka albo pasa ruchu.',
    'T-1b': 'Długość tunelu albo odległość do jego końca.',
    'T-2': 'Długość odcinka, na którym niebezpieczeństwo się powtarza. Koniec tego odcinka wskazuje tabliczka T-3.',
    'T-3': 'Koniec odcinka oznaczonego wcześniej tabliczką T-1 lub T-2.',
    'T-3a': 'Koniec miejsca przeznaczonego na postój.',
    'T-4': 'Liczba zakrętów na odcinku oznaczonym znakiem A-3 lub A-4.',
    'T-5': 'Początek drogi krętej - serii zakrętów bez prostych odcinków.',
    'T-6a': 'Rzeczywisty przebieg drogi z pierwszeństwem przez skrzyżowanie, umieszczana na tej właśnie drodze. Gruba linia to droga z pierwszeństwem - jeżeli skręca, jadąc na wprost tracisz pierwszeństwo. To jedna z najczęstszych pułapek egzaminacyjnych.',
    'T-6b': 'Układ dróg podporządkowanych widziany z drogi z pierwszeństwem.',
    'T-6c': 'Rzeczywisty przebieg drogi z pierwszeństwem, umieszczana na drodze podporządkowanej - pokazuje, komu masz ustąpić.',
    'T-6d': 'Prostopadły przebieg drogi z pierwszeństwem wraz z układem dróg podporządkowanych, widziany z drogi podporządkowanej.',
    'T-7': 'Układ torów i drogi na przejeździe kolejowym.',
    'T-8': 'Miejsce, w którym ruch pojazdów skierowano na tory tramwajowe.',
    'T-9': 'Rzeczywista wartość spadku lub wzniesienia drogi w procentach.',
    'T-10': 'Bocznica kolejowa lub tor o podobnym charakterze - przejeżdżają nim pojedyncze wagony, często bez zapowiedzi.',
    'T-11': 'Przeprawa promowa.',
    'T-12': 'Podłużny uskok nawierzchni, groźny zwłaszcza dla jednośladów.',
    'T-13': 'Odcinek z koleinami. W deszczu koleiny zbierają wodę i sprzyjają poślizgowi.',
    'T-14': 'Miejsce częstych wypadków; rodzaj zdarzeń pokazuje symbol na tabliczce.',
    'T-14a': 'Miejsce częstych zderzeń z poprzedzającymi pojazdami - typowe tam, gdzie kolumna nagle staje.',
    'T-14b': 'Miejsce częstych zderzeń czołowych.',
    'T-14c': 'Miejsce częstych zderzeń z tramwajami.',
    'T-14d': 'Przejazd kolejowy o warunkach szczególnie sprzyjających wypadkom.',
    'T-15': 'Miejsce częstych wypadków przy mokrej nawierzchni.',
    'T-16': 'Miejsce wyjazdu pojazdów uprzywilejowanych wskazanych na tabliczce.',
    'T-16a': 'Miejsce wyjazdu karetek pogotowia.',
    'T-17': 'Granica państwa.',
    'T-18': 'Nieoczekiwana zmiana kierunku ruchu o przebiegu pokazanym na tabliczce.',
    'T-18a': 'Nieoczekiwana zmiana kierunku: najpierw w prawo, potem w lewo.',
    'T-18b': 'Nieoczekiwana zmiana kierunku w lewo.',
    'T-18c': 'Nieoczekiwana zmiana kierunku w prawo.',
    'T-19': 'Świeżo malowane znaki poziome - farba brudzi i jest śliska.',
    'T-20': 'Długość odcinka, na którym obowiązuje zakaz ze znaku, pod którym wisi tabliczka.',
    'T-21': 'Odległość od znaku do miejsca, w którym zakaz zaczyna obowiązywać.',
    'T-23a': 'Zakaz lub nakaz ze znaku dotyczy wyłącznie motocykli.',
    'T-23b': 'Dotyczy samochodów ciężarowych i pojazdów specjalnych powyżej 3,5 t oraz ciągników samochodowych.',
    'T-23c': 'Dotyczy ciągników rolniczych i pojazdów wolnobieżnych.',
    'T-23d': 'Dotyczy pojazdów silnikowych z przyczepą, poza przyczepą jednoosiową i naczepą.',
    'T-23e': 'Dotyczy pojazdów z przyczepą kempingową.',
    'T-23f': 'Dotyczy autobusów.',
    'T-23g': 'Dotyczy trolejbusów.',
    'T-23h': 'Dotyczy pojazdów przewożących towary niebezpieczne.',
    'T-23i': 'Dotyczy pojazdów z towarami wybuchowymi lub łatwopalnymi.',
    'T-23j': 'Dotyczy pojazdów z towarami mogącymi skazić wodę.',
    'T-24': 'Pojazd pozostawiony w tym miejscu zostanie odholowany na koszt właściciela.',
    'T-25a': 'Początek zakazu postoju lub zatrzymywania - strzałka skierowana w jedną stronę.',
    'T-25b': 'Kontynuacja zakazu postoju lub zatrzymywania na dalszym odcinku.',
    'T-25c': 'Koniec zakazu postoju lub zatrzymywania.',
    'T-26': 'Zakaz postoju lub zatrzymywania dotyczy strony placu, a nie odcinka ulicy.',
    'T-27': 'Przejście szczególnie uczęszczane przez dzieci. Wymaga wyraźnego zwolnienia i gotowości do zatrzymania.',
    'T-28': 'Za przejazd tą drogą pobierana jest opłata.',
    'T-28a': 'Koniec odcinka płatnego.',
    'T-29': 'Miejsce postojowe dla pojazdu osoby niepełnosprawnej. Zajęcie go bez uprawnienia jest wykroczeniem zagrożonym wysoką karą.',
    'T-30': 'Sposób ustawienia pojazdu względem krawędzi jezdni na wyznaczonym miejscu postojowym.',
    'T-30a': 'Postój całego pojazdu na chodniku, równolegle do krawężnika.',
    'T-30b': 'Postój całego pojazdu na chodniku, prostopadle do krawężnika.',
    'T-30c': 'Postój całego pojazdu na chodniku, skośnie do krawężnika.',
    'T-30d': 'Postój na chodniku kołami przedniej osi, prostopadle do krawężnika.',
    'T-30e': 'Postój na chodniku kołami przedniej osi, skośnie do krawężnika.',
    'T-30f': 'Postój całego pojazdu na jezdni, prostopadle do krawężnika.',
    'T-30g': 'Postój całego pojazdu na jezdni, skośnie do krawężnika.',
    'T-30h': 'Postój na chodniku kołami jednego boku, równolegle do krawężnika.',
    'T-30i': 'Postój całego pojazdu na jezdni, równolegle do krawężnika.',
    'T-31': 'Kategoria tunelu, decydująca o tym, jakie towary niebezpieczne wolno nim przewozić.',
    'T-31a': 'Tunel kategorii A.',
    'T-31b': 'Tunel kategorii B.',
    'T-31c': 'Tunel kategorii C.',
    'T-31d': 'Tunel kategorii D.',
    'T-31e': 'Tunel kategorii E.',
    'T-32': 'Minimalny odstęp od poprzedzającego pojazdu, jaki trzeba zachować.',
    'T-33': 'W zatoce znajduje się telefon alarmowy i gaśnica.',
    'T-34': 'Za przejazd pobierana jest opłata elektroniczna.',

    # ---------------------------------------------------------------- P ----
    'P-1': 'Linia pojedyncza przerywana - kreski krótsze od przerw. Wyznacza pasy ruchu i wolno ją przejeżdżać. Gdy kreski i przerwy są równe, a linia podwójnej szerokości, pas jest zanikający, powolny albo prowadzi wyłącznie na inną drogę.',
    'P-2': 'Linia pojedyncza ciągła - oddziela pasy o tym samym kierunku ruchu lub jezdnię od pobocza. Nie wolno jej przejeżdżać ani najeżdżać.',
    'P-3': 'Linia jednostronnie przekraczalna: ciągła z przerywaną obok. Wolno ją przejechać od strony linii przerywanej, nie wolno od strony ciągłej.',
    'P-4': 'Linia podwójna ciągła - rozdziela przeciwne kierunki ruchu. Przejeżdżanie i najeżdżanie jest zabronione, co wyklucza także skręt w lewo przez tę linię.',
    'P-5': 'Linia podwójna przerywana - oznacza pas o zmiennym kierunku ruchu, sterowany sygnalizacją nad jezdnią.',
    'P-6': 'Linia ostrzegawcza: kreski dłuższe od przerw. Uprzedza, że zaraz zacznie się linia ciągła - to ostatni moment na wyprzedzanie.',
    'P-7a': 'Linia krawędziowa przerywana - wyznacza krawędź jezdni; wolno ją przejeżdżać.',
    'P-7b': 'Linia krawędziowa ciągła - pobocze za nią nie jest przeznaczone do ruchu; nie wolno jej przejeżdżać.',
    'P-8a': 'Strzałka kierunkowa na wprost - z tego pasa jedzie się prosto.',
    'P-8b': 'Strzałka kierunkowa do skręcania - wskazuje dozwolony kierunek z danego pasa.',
    'P-8c': 'Strzałka kierunkowa do zawracania.',
    'P-9': 'Strzałka naprowadzająca - zapowiada konieczność zmiany pasa, bo obecny zaraz się kończy.',
    'P-10': 'Przejście dla pieszych - poprzeczne białe pasy, popularnie zebra.',
    'P-11': 'Przejazd dla rowerzystów, oznaczony kwadratami.',
    'P-12': 'Gruba linia poprzeczna przy znaku B-20 - wyznacza miejsce bezwzględnego zatrzymania.',
    'P-13': 'Linia z trójkątów przy znaku A-7 - miejsce warunkowego zatrzymania, gdy trzeba ustąpić pierwszeństwa.',
    'P-14': 'Linia z prostokątów - miejsce warunkowego zatrzymania przed sygnalizacją albo przejściem.',
    'P-15': 'Trójkąt podporządkowania namalowany na jezdni - powtarza znaczenie znaku A-7.',
    'P-16': 'Napis STOP na jezdni, towarzyszący znakowi B-20.',
    'P-17': 'Linia przystankowa - wyznacza miejsce zatrzymania autobusu lub tramwaju.',
    'P-18': 'Stanowisko postojowe.',
    'P-19': 'Linia wyznaczająca pas postojowy.',
    'P-20': 'Koperta - stanowisko zastrzeżone dla konkretnego pojazdu lub grupy pojazdów.',
    'P-21': 'Powierzchnia wyłączona, w ukośne pasy. Nie wolno na nią wjeżdżać ani się na niej zatrzymywać.',
    'P-22': 'Napis BUS - pas przeznaczony dla autobusów.',
    'P-23': 'Symbol roweru - droga lub pas dla rowerów.',
    'P-24': 'Symbol wózka - miejsce dla pojazdu osoby niepełnosprawnej.',
    'P-25': 'Próg zwalniający zaznaczony na jezdni.',
    'P-26': 'Symbol pieszego - droga lub jej część przeznaczona dla pieszych.',
    'P-27': 'Kierunek i tor ruchu roweru - prowadzi rowerzystę przez skrzyżowanie.',
}
